# Data Preprocessing

In [9]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pathlib import Path

## Building a Table for the Dataset

In [17]:

def build_table(folder):
    rows = []
    for class_dir in Path(folder).iterdir():
        if class_dir.is_dir():
            for img_path in class_dir.iterdir():
                if img_path.suffix.lower() in {".jpg", ".jpeg", ".png"}:
                    rows.append({"Path": str(img_path), "Labels": class_dir.name})
    return pd.DataFrame(rows)

train_df = build_table("../data/Training")
test_df = build_table("../data/Testing")

train_df.to_csv("../data/train.csv", index=False)
test_df.to_csv("../data/test.csv", index=False)

In [18]:
train_df = pd.read_csv("../data/train.csv")

In [19]:
train_df.head()

                                        Path     Labels
0   ../data/Training/pituitary/Tr-pi_766.jpg  pituitary
1  ../data/Training/pituitary/Tr-pi_1169.jpg  pituitary
2   ../data/Training/pituitary/Tr-pi_772.jpg  pituitary
3   ../data/Training/pituitary/Tr-pi_982.jpg  pituitary
4  ../data/Training/pituitary/Tr-pi_1141.jpg  pituitary

## Validation split
Training/Validation/Testing split

In [20]:
# Since We do not have a validation split we will make one here.


X = train_df['Path']
y = train_df['Labels']

X_train, X_val, y_train, Y_val= train_test_split(X, y, test_size=0.25, stratify=y ,random_state=42)

pd.DataFrame(X_val).assign(target=Y_val).to_csv("../data/val.csv", index=False)

In [22]:
val_df = pd.read_csv("../data/val.csv")
val_df.head()

                                           Path      target
0     ../data/Training/meningioma/Tr-me_757.jpg  meningioma
1         ../data/Training/glioma/Tr-gl_957.jpg      glioma
2  ../data/Training/meningioma/Tr-aug-me_93.jpg  meningioma
3        ../data/Training/notumor/Tr-no_719.jpg     notumor
4         ../data/Training/notumor/Tr-no_11.jpg     notumor